# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form.setFixedSize(610, 618)
        Form.setAcceptDrops(False)
        Form.setStyleSheet("background: gray; color: black;")
        font = QtGui.QFont()
        font.setBold(True)
        Form.setFont(font)

        self.bracket_to_right = QtWidgets.QPushButton(parent=Form)
        self.bracket_to_right.setShortcut(QtGui.QKeySequence('('))
        self.bracket_to_right.hide()

        self.bracket_to_left = QtWidgets.QPushButton(parent=Form)
        self.bracket_to_left.setShortcut(QtGui.QKeySequence(')'))
        self.bracket_to_left.hide()

        self.btn1 = QtWidgets.QPushButton(parent=Form)
        self.btn1.setGeometry(QtCore.QRect(10, 370, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn1.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn1.setObjectName("btn1")
        self.btn4 = QtWidgets.QPushButton(parent=Form)
        self.btn4.setGeometry(QtCore.QRect(10, 250, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn4.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn4.setObjectName("btn4")
        self.zero = QtWidgets.QPushButton(parent=Form)
        self.zero.setGeometry(QtCore.QRect(10, 490, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.zero.setFont(font)
        self.zero.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.zero.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.zero.setObjectName("zero")
        self.float_number = QtWidgets.QPushButton(parent=Form)
        self.float_number.setGeometry(QtCore.QRect(250, 490, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.float_number.setFont(font)
        self.float_number.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.float_number.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.float_number.setObjectName("float_number")
        self.btn3 = QtWidgets.QPushButton(parent=Form)
        self.btn3.setGeometry(QtCore.QRect(250, 370, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn3.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(parent=Form)
        self.btn2.setGeometry(QtCore.QRect(130, 370, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn2.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn2.setObjectName("btn2")
        self.btn5 = QtWidgets.QPushButton(parent=Form)
        self.btn5.setGeometry(QtCore.QRect(130, 250, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn5.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(parent=Form)
        self.btn6.setGeometry(QtCore.QRect(250, 250, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn6.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn6.setObjectName("btn6")
        self.btn9 = QtWidgets.QPushButton(parent=Form)
        self.btn9.setGeometry(QtCore.QRect(250, 130, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn9.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn9.setObjectName("btn9")
        self.btn7 = QtWidgets.QPushButton(parent=Form)
        self.btn7.setGeometry(QtCore.QRect(10, 130, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn7.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(parent=Form)
        self.btn8.setGeometry(QtCore.QRect(130, 130, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn8.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.btn8.setObjectName("btn8")
        self.minus = QtWidgets.QPushButton(parent=Form)
        self.minus.setGeometry(QtCore.QRect(370, 130, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.minus.setFont(font)
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.minus.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.minus.setObjectName("minus")
        self.plus = QtWidgets.QPushButton(parent=Form)
        self.plus.setGeometry(QtCore.QRect(370, 250, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.plus.setFont(font)
        self.plus.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.plus.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.plus.setObjectName("plus")
        self.result = QtWidgets.QPushButton(parent=Form)
        self.result.setGeometry(QtCore.QRect(490, 130, 111, 471))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.result.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.result.setObjectName("result")
        self.division = QtWidgets.QPushButton(parent=Form)
        self.division.setGeometry(QtCore.QRect(370, 370, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.division.setFont(font)
        self.division.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.division.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.division.setObjectName("division")
        self.multiplication = QtWidgets.QPushButton(parent=Form)
        self.multiplication.setGeometry(QtCore.QRect(370, 490, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.multiplication.setFont(font)
        self.multiplication.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.multiplication.setStyleSheet("QPushButton {\n"
"    background: orange;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ebac00;\n"
"}")
        self.multiplication.setObjectName("multiplication")
        self.instance = QtWidgets.QLineEdit(parent=Form)
        self.instance.setGeometry(QtCore.QRect(10, 10, 581, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.instance.setFont(font)
        self.instance.setStyleSheet("color: black;\n"
"background: white;\n"
"border-radius: 20px;\n"
"padding-left: 10px;")
        self.instance.setDragEnabled(True)
        self.instance.setObjectName("instance")
        # self.instance.setEnabled(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.add_menu_bar(MainWindow=Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ACalculator"))
        self.btn1.setText(_translate("Form", "1"))
        self.btn4.setText(_translate("Form", "4"))
        self.zero.setText(_translate("Form", "0"))
        self.float_number.setText(_translate("Form", "."))
        self.btn3.setText(_translate("Form", "3"))
        self.btn2.setText(_translate("Form", "2"))
        self.btn5.setText(_translate("Form", "5"))
        self.btn6.setText(_translate("Form", "6"))
        self.btn9.setText(_translate("Form", "9"))
        self.btn7.setText(_translate("Form", "7"))
        self.btn8.setText(_translate("Form", "8"))
        self.minus.setText(_translate("Form", "-"))
        self.plus.setText(_translate("Form", "+"))
        self.result.setText(_translate("Form", "="))
        self.division.setText(_translate("Form", "/"))
        self.multiplication.setText(_translate("Form", "*"))
        self.instance.setPlaceholderText(_translate("Form", "Example text"))

    def add_menu_bar(self, MainWindow):
        menuBar = QtWidgets.QMenuBar(MainWindow)
        window_menu = QtWidgets.QMenu('&Вікно', MainWindow)
        self.clear_btn = QtGui.QAction('Очистити')
        self.clear_btn.setShortcut(QtGui.QKeySequence('a'))
        self.delete_symbol_btn = QtGui.QAction('Видалити символ')
        self.delete_symbol_btn.setShortcut(QtGui.QKeySequence('Ctrl+Delete'))
        window_menu.addAction(self.clear_btn)
        window_menu.addAction(self.delete_symbol_btn)
        menuBar.addMenu(window_menu)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
